version: "3.7"
services:
  model_predictor:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    restart: on-failure
    volumes:
      - ../../checkpoints:/sample_solution/checkpoints
      - ../../configs:/sample_solution/configs
    ports:
      - ${PORT}:5040
    environment:
      MODEL_CONFIG_PATH: ${MODEL_CONFIG_PATH}
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/sh -c "python -m src.app  --port 5040"